export const KeyCombinations = {
  CTRL_A: 'ctrl + a',
  CTRL_C: 'ctrl + c',
  CTRL_ENTER: 'ctrl + enter',
  SHIFT_ENTER: 'shift + enter',
  ALT_ENTER: 'alt + enter',
  ENTER: 'enter',
  TAB: 'tab',
  CTRL_G: 'ctrl + g',
  CTRL_MINUS: 'ctrl + -',
  CTRL_PLUS: 'ctrl + +',
  CTRL_S: 'ctrl + s',
  CTRL_1: 'ctrl + 1',
  CTRL_3: 'ctrl + 3',
  CTRL_0: 'ctrl + 0',
  CTRL_E: 'ctrl + e',
  CTRL_SHIFT_J: 'ctrl + shift + j',
  CTRL_SHIFT_K: 'ctrl + shift + k',
  CTRL_5: 'ctrl + 5',
  CTRL_6: 'ctrl + 6',
  CTRL_7: 'ctrl + 7',
};
